#!/bin/bash
#
#kolmnurk
#
#read
#
#alumine pool
for((r=4; r>0; r--))
do
	#veerud - täpid
	#tärnive arv algab 1-st
	#igal real ei tohi tärnide arv ületada rea numbrit
	for ((t=1; t<$r; t++))
	do
	echo -n "o "
	done
	#tärnid
	#tärnide arv algab 1-st
	#igal real ei tohi tärnide arv ületada 4-$r +2
	for ((t=1; t<$((4 - $r + 2)); t++))
	do
	echo -n "* "
	done
	echo #reavahetus
done
 #alumine pool
#for((r=4; r>0; r--))
#do
	#for((t=1; t<$(($r+1)); t++))
	#do
	#echo -n "* "
	#done
	#echo #reavahetus
#done
