#!/bin/bash
#
#kolmnurk
#
#read
#
#alumine pool
echo "Sisesta ridade arv: "
read ridade_arv
for((r=1; r<$(($ridade_arv+1)); r++))
do
	#veerud - täpid
	#tärnive arv algab 1-st
	#igal real ei tohi tärnide arv ületada rea numbrit
	for ((t=1; t<$(($r +1)); t++))
		do
		echo -n "o "
	done
	#tärnid
	#tärnide arv algab 1-st
	#igal real ei tohi tärnide arv ületada 4-$r +2
	for ((t=1; t<$(($ridade_arv - $r + 1)); t++))
		do
		echo -n "* "
	done
	echo #reavahetus
done
