#!/bin/bash
#
# tärniruut
#
# tekitame read
for ((r=1; r<5; r++))
 do
	#kontrollige kui r on 1 voi (-o) r on 4
	if [ $r -eq 1 -o $r -eq 4 ]; then
		# joonistame tärnid
		for((v=1; v<6; v++))
		do
			echo -n "* "
		done
	#kõik vahepealsed read
	else
	#tärn
	echo -n "* "
	#täpid
	for((v=2; v<5; v++))
	do
	echo -n "  "
	done
	#tärn
	echo -n "* "
	fi
	# reavahetus
	echo
done
