#!/bin/bash
#
#keskkonna ja oma muutujate kasutamine
#
#kasutame keskkonna muutuja nimega $USER
#tervitame kasutajat
echo "Tere, $USER!"
#kuupäeva väärtuse loomine
#sefineerime vastava väärtusega muutujaga 
kuupaev=`date +'%d. %B'`
#väljastame kuupäev koos seletusega
echo "Täna on $kuupaev"
#kella väärtuse loomine
#defineerime vastava väärtusega muutuja
kell=`date +'%H:%M'`
#väljastame kell koos seletusega
echo "Kell on $kell"
#kuu väärtuse loomine
#defineerime vastava väärtusega muutuja
kalender=`cal`
#väljastame kuu koos seletusega
echo "Antud kuu kalender: "
echo "---------------------"
echo "$kalender"
echo "---------------------"

